import type { SortAlgorithm, SortInfo } from '../sortingTypes';

export const SORT_INFO: Record<SortAlgorithm, SortInfo> = {
  bubble: {
    label: 'Bubble Sort',
    concept: 'Bubble sort repeatedly compares neighboring values and swaps them when they are out of order. Large values bubble toward the end after each pass.',
    timeComplexity: 'O(n²) average/worst, O(n) best with early exit',
    spaceComplexity: 'O(1)',
    useCases: ['Teaching comparisons and swaps', 'Tiny arrays', 'Nearly sorted data with early exit'],
    edgeCases: ['Empty arrays', 'Duplicate values', 'Already sorted arrays'],
    pseudocode: [
      'for end from n - 1 down to 1',
      '  swapped = false',
      '  for i from 0 to end - 1',
      '    if array[i] > array[i + 1]',
      '      swap array[i], array[i + 1]',
      '      swapped = true',
      '  if not swapped: break',
    ],
  },
  selection: {
    label: 'Selection Sort',
    concept: 'Selection sort divides the array into sorted and unsorted regions. Each pass selects the smallest unsorted item and places it at the next sorted position.',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    useCases: ['Teaching minimum selection', 'When writes should be limited', 'Small arrays'],
    edgeCases: ['Duplicate minimums', 'Already sorted arrays', 'Single-item arrays'],
    pseudocode: [
      'for i from 0 to n - 1',
      '  minIndex = i',
      '  for j from i + 1 to n - 1',
      '    if array[j] < array[minIndex]',
      '      minIndex = j',
      '  swap array[i], array[minIndex]',
    ],
  },
  insertion: {
    label: 'Insertion Sort',
    concept: 'Insertion sort grows a sorted prefix. Each new value is inserted into the correct position by shifting larger values right.',
    timeComplexity: 'O(n²) average/worst, O(n) best',
    spaceComplexity: 'O(1)',
    useCases: ['Small arrays', 'Nearly sorted data', 'Online insertion as values arrive'],
    edgeCases: ['Reverse sorted arrays', 'Duplicates', 'Negative values'],
    pseudocode: [
      'for i from 1 to n - 1',
      '  key = array[i]',
      '  j = i - 1',
      '  while j >= 0 and array[j] > key',
      '    array[j + 1] = array[j]',
      '    j = j - 1',
      '  array[j + 1] = key',
    ],
  },
  merge: {
    label: 'Merge Sort',
    concept: 'Merge sort recursively splits the array into halves, sorts each half, then merges sorted halves back together.',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    useCases: ['Stable sorting', 'Large datasets', 'Linked-list sorting'],
    edgeCases: ['Empty halves', 'Odd-sized ranges', 'Many duplicate values'],
    pseudocode: [
      'mergeSort(left, right)',
      '  if left >= right: return',
      '  mid = floor((left + right) / 2)',
      '  mergeSort(left, mid)',
      '  mergeSort(mid + 1, right)',
      '  merge the two sorted halves',
    ],
  },
  quick: {
    label: 'Quick Sort',
    concept: 'Quick sort chooses a pivot, partitions values around it, then recursively sorts the partitions.',
    timeComplexity: 'O(n log n) average, O(n²) worst',
    spaceComplexity: 'O(log n) average recursion stack',
    useCases: ['Fast in-memory sorting', 'Teaching divide and conquer', 'Systems programming variants'],
    edgeCases: ['Bad pivot choices', 'Already sorted input', 'Many duplicates'],
    pseudocode: [
      'quickSort(low, high)',
      '  if low >= high: return',
      '  pivot = array[high]',
      '  partition values <= pivot to the left',
      '  place pivot in final position',
      '  quickSort(low, pivotIndex - 1)',
      '  quickSort(pivotIndex + 1, high)',
    ],
  },
};
